siriuspy/siriuspy/csdevice/__init__.py, siriuspy/siriuspy/pwrsupply/pru.py
=> Cleanup code

CODEOWNERS, siriuspy/siriuspy/pwrsupply/model.py
- also, it seems that there was a bugin connection state check of ps. fixed.
- fixed CODEOWNERS mistake.
=> Pr improve conn check ps

siriuspy/siriuspy/pwrsupply/beaglebone.py
- changed how classes creates PSs for the bench tests.
- had to tmp. change BeagleBone class.
=> Pr original bbb file

.travis.yml
Changed travis.yml to check only master
=> Configure Travis to test only the master branch

siriuspy/siriuspy/epics/computed_pv.py, siriuspy/siriuspy/pwrsupply/model.py, siriuspy/siriuspy/thread.py, siriuspy/tests/pwrsupply/test_sync.py
Hi guys, I took a look at the Class `QueueThread` defined in module `computed_pv` and fount it very interesting!!
I plan to use this Class in the `timesys` package, so I have generalized it a little bit and changed its location to the new module `thread`, where I also added a Class that I had already been using in `timesys` module from `machine-applications` repo.
=> Pr thread module

siriuspy/examples/bbb_tests/test_pru_sync.py, siriuspy/siriuspy/bsmp/serial.py, siriuspy/siriuspy/pwrsupply/beaglebone.py, siriuspy/siriuspy/pwrsupply/model.py, siriuspy/siriuspy/pwrsupply/pru.py
- Now AS-PS can change to cycle and back to slowref
=> Pr new bbb

siriuspy/siriuspy/pwrsupply/beaglebone.py, siriuspy/siriuspy/pwrsupply/bsmp.py, siriuspy/siriuspy/pwrsupply/pru.py, siriuspy/tests/pwrsupply/test_e2scontroller.py
Implemented new scheme for SlowRefSync operation mode
=> Pr slowrefsync orig

siriuspy/siriuspy/pwrsupply/bbbtests.py, siriuspy/siriuspy/pwrsupply/beaglebone.py, siriuspy/siriuspy/pwrsupply/controller.py, siriuspy/siriuspy/pwrsupply/e2scontroller.py, siriuspy/siriuspy/pwrsupply/pru.py, siriuspy/siriuspy/pwrsupply/prucontroller.py, siriuspy/tests/pwrsupply/test_beaglebone.py, siriuspy/tests/pwrsupply/test_pru.py
- processes can now create more than one instances of PRUController objects.
- A PRUController object can now interact with more than 4 BSMP slaves.
=> Pr parallel prucontrollers

siriuspy/siriuspy/__init__.py, siriuspy/siriuspy/callbacks.py, siriuspy/siriuspy/util.py, siriuspy/tests/test_callbacks.py
Hi guys, the main features of this PR are:
- fix bug in `configure_log_file` function of `util.py` module.
- Create a module called `callbacks.py` with a class called `Callback` to serve as a general purpose callback handler for our applications.
=> Callback class

siriuspy/siriuspy/search/ps_search.py, siriuspy/siriuspy/servweb/implementation.py, siriuspy/tests/search/test_ps_search.py, siriuspy/tests/servweb/test_implementation.py
Add methods related to bsmp-dclink mapping in servweb and pssearch mo…
=> BSMP-DCLink Mapping

siriuspy/siriuspy/ramp/conn.py
This PR adds a SOFB connector and adds interlocks and ramp increase checks to MA and RF connectors.
=> Complement ramp subpackage connectors

README.md, requirements.txt, siriuspy/requirements.txt, siriuspy/setup.py, siriuspy/siriuspy/envars.py, siriuspy/tests/__init__.py
* update `README.md`
* update `requirements.txt`
* enforce requeriments in `setup.py`
* make sure unittests are run without access to servers
=> Update readme.md and package requirements

siriuspy/siriuspy/csdevice/orbitcorr.py
=> BUG: remove two dots from trigger name.

siriuspy/siriuspy/csdevice/bpms.py, siriuspy/siriuspy/csdevice/orbitcorr.py, siriuspy/siriuspy/timesys/hl_classes.py, siriuspy/siriuspy/timesys/ll_classes.py
This PR includes several small bug fixes for Timing and SOFB IOCs.
=> Fix SOFB and Timing 

siriuspy/siriuspy/envars.py, siriuspy/tests/pwrsupply/test_watcher.py
- Needs merging of `PR-update-servers` in `lnls-sirius/scripts`
=> Update URL for servweb in envars.py

CODEOWNERS, siriuspy/siriuspy/search/hl_time_search.py, siriuspy/siriuspy/search/ll_time_search.py, siriuspy/siriuspy/timesys/ll_classes.py
Timing related updates:
- Fix some bugs;
- improve IOCs initialization;
- improve performance;
Update `CODEOWNERS` file.
=> Timing updates

siriuspy/siriuspy/servconf/conf_service.py
- Change to check if config name is valid when inserting new configuration;
- Fix bug in reading configs with some reserved characters.
=> Fix bugs in ConfigService.

siriuspy/siriuspy/timesys/ll_classes.py
Now instead of calling itself, a loop was implemented when setting the PV.
=> TIM.BUG: Fix max recursive call of lock_thread. 

siriuspy/siriuspy/pwrsupply/bsmp.py, siriuspy/siriuspy/pwrsupply/functions.py, siriuspy/siriuspy/pwrsupply/prucontroller.py
=> Pr update pwrsupply classes

siriuspy/siriuspy/pwrsupply/prucontroller.py
- fix bug introduced in commit that supposedly simplified the implementation of PRU curve changes. The bug was due to repeated variable name.
=> Fix bug introduced in recent commit (PRUController Curves)

siriuspy/siriuspy/clientconfigdb/types/global_config.py
=> Add PwrState-Sel to global_config template

siriuspy/siriuspy/pwrsupply/beaglebone.py, siriuspy/siriuspy/pwrsupply/pru.py, siriuspy/siriuspy/pwrsupply/prucontroller.py
This pull request allow for PS IOCs to be run inside BBBs or as EthPRUserial485 clients, outside the beaglebones. There is a accompanying PR in `machine-applications` repo.
=> Power Supply IOCs In/Out Beaglebones

siriuspy/siriuspy/epics/pv_time_serie.py, siriuspy/tests/optics/test_opticscorr.py
...and fix bug in SiriusPVTimeSerie class.
=> Add tests to optics/opticscorr.py

siriuspy/siriuspy/pwrsupply/bsmp.py, siriuspy/siriuspy/pwrsupply/bsmp_sim.py, siriuspy/siriuspy/pwrsupply/model_factory.py
Just variable renaming. No change in IOC behaviour
=> Update psmodel FBP_DCLink

siriuspy/siriuspy/csdevice/pwrsupply.py, siriuspy/siriuspy/pwrsupply/bsmp.py, siriuspy/siriuspy/pwrsupply/bsmp_sim.py, siriuspy/siriuspy/pwrsupply/model_factory.py
- Add pvs _LoadVoltage-Mon_, _InductorsTemperature-Mon_, _IGBTSTemperature-Mon_ and _PWMDutyCycle-Mon_.
- **real IOC tests tested!**
=> Update psmodel FAC_DCDC

siriuspy/siriuspy/csdevice/pwrsupply.py, siriuspy/siriuspy/pwrsupply/bsmp.py, siriuspy/siriuspy/pwrsupply/bsmp_sim.py, siriuspy/siriuspy/pwrsupply/model_factory.py
add PVs
- _IIB1InductorsTemperature-Mon_
- _IIB1HeatSinkTemperature-Mon_
- _IIB2InductorsTemperature-Mon_
- _IIB2HeatSinkTemperature-Mon_
- _IntlkIIB1-Mon and IntlkIIB2-Mon_
=> Update psmodel FAC_2S_DCDC

requirements.txt
=> Update python package six to 1.12.0

siriuspy/siriuspy/clientarch/client.py
Create _make_request method to only use login session when needed.
=> Improve ClientArch lib

siriuspy/siriuspy/pwrsupply/beaglebone.py, siriuspy/siriuspy/pwrsupply/psupply.py, siriuspy/siriuspy/pwrsupply/tests/TODO.txt
- add parameter init is PSupply class
=> Make siggen parms independent for pwrsupplies in the same UDC

siriuspy/siriuspy/pwrsupply/beaglebone.py
Still needs testing with pwrsupply topologies other than (TB quads , TS CVs)! **done!**
=> Fix bugs in new BeagleBone factory

siriuspy/siriuspy/clientconfigdb/types/bo_ramp.py, siriuspy/siriuspy/ramp/norm_factory.py, siriuspy/siriuspy/ramp/ramp.py, siriuspy/siriuspy/ramp/test_norm_factory.py
* Normalized configs are contained in BoosterRamp configurations, they are not lists of config server names anymore.
=> ramp.ENH: add new version

siriuspy/siriuspy/csdevice/orbitcorr.py
see lnls-sirius/machine-applications#176
=> Add DeltaKicks setters.

siriuspy/siriuspy/cycle/conn.py, siriuspy/siriuspy/cycle/main.py, siriuspy/siriuspy/cycle/util.py
Change PSCycle to set all SI PS currents to zero in prepare_ps_parameters, remove BO and fix order in checking final state
=> Update cycle package

siriuspy/siriuspy/devices/__init__.py, siriuspy/siriuspy/devices/energy.py, siriuspy/siriuspy/devices/syncd.py
- and refactor Energy device to use DevicesSync
=> Add DevicesSync to devices

siriuspy/siriuspy/sofb/bpms.py, siriuspy/siriuspy/sofb/csdev.py, siriuspy/siriuspy/sofb/orbit.py
Implement control of non-linear correction of measured orbit by application of 9th order bivariate polynome to the raw data.
=> Upgrade SOFB

siriuspy/siriuspy/cycle/conn.py, siriuspy/siriuspy/namesys/implementation.py
- Standardize throwaway comment.
=> Standardize and Cleanup (Cont.)

siriuspy/siriuspy/devices/device.py, siriuspy/siriuspy/simul/__init__.py, siriuspy/siriuspy/simul/simfactory.py, siriuspy/siriuspy/simul/simps.py, siriuspy/siriuspy/simul/simpv.py, siriuspy/siriuspy/simul/simulation.py, siriuspy/siriuspy/simul/simulator.py
- Add simulator `SimPUTypeModel`
- Killed bugs that surfaced when `SimPV` and _Simulators_ were used together.
=> Add Simulator Factory

siriuspy/siriuspy/devices/device.py, siriuspy/siriuspy/devices/psconv.py, siriuspy/siriuspy/devices/pssofb.py, siriuspy/siriuspy/pwrsupply/csdev.py, siriuspy/siriuspy/simul/__init__.py, siriuspy/siriuspy/simul/simfactory.py, siriuspy/siriuspy/simul/simps.py, siriuspy/siriuspy/simul/simpv.py, siriuspy/siriuspy/simul/simulation.py, siriuspy/siriuspy/simul/simulator.py
Requires PR https://github.com/lnls-sirius/dev-packages/pull/433
=> PSCorrSOFB and PSApplySOFB devices

siriuspy/siriuspy/magnet/excdata.py
This PR allows for rescaling excitation curves for each power supply type. A configurable additional parameter `rescaling_factor` is added to each excdata file header. Its default value is 1.0
=> Excitation Data Rescaling Factor

siriuspy/siriuspy/devices/device.py, siriuspy/siriuspy/devices/sofb.py
- Improve `devices.SOFB` to correctly deal with SinglePass and MultiTurn trajectories.
=> Improve SOFB Device

siriuspy/siriuspy/clientarch/devices.py
- transform attributes into class properties to avoid comm with consts server during import time.
=> CLTARCH.BUG: fix import error:

siriuspy/siriuspy/devices/psconv.py, siriuspy/siriuspy/magnet/factory.py, siriuspy/siriuspy/magnet/normalizer.py, siriuspy/siriuspy/magnet/util.py, siriuspy/siriuspy/pwrsupply/csdev.py, siriuspy/siriuspy/search/ps_search.py
=> APU22 Phase->Kx conversion

siriuspy/siriuspy/currinfo/lifetime/main.py, siriuspy/siriuspy/pwrsupply/csdev.py, siriuspy/siriuspy/search/__init__.py, siriuspy/siriuspy/search/id_search.py, siriuspy/siriuspy/util.py, siriuspy/tests/search/test_init.py
This PR also:
- fix a bug in pwrsupply.csdev.py
- fix comments in util.conv_splims_labels
- add missing reset buffer command in SI Lifetime IOC
=> Add IDSearch

siriuspy/siriuspy/sofb/bpms.py
Fix antenna selection for BPM position algebra (singlepass) (on behalf of fernando h. de sá)
=> Fix antenna selection for BPM position algebra (singlepass)

siriuspy/siriuspy/pwrsupply/pssofb.py, siriuspy/siriuspy/pwrsupply/tests/sofb2bsmp.py, siriuspy/siriuspy/thread.py
Reuse the same threads to perform all setpoints of PSSOFB.
Introduce a general purpose class, `siriuspy.thread.AsynchronousWorker` to hande this type o jobs.
=> Pssofb same threads

siriuspy/siriuspy/pwrsupply/pructrl/pru.py, siriuspy/tests/pwrsupply/pructrl/test_pru.py
please, check lnls-sirius/eth-bridge-pru-serial485#26.
Tested!
=> Adapt PRU to new EthBridgeClient

siriuspy/siriuspy/pwrsupply/pructrl/pru.py
@fernandohds564, this fix is supposed to be merged after "Adapt" PR is merged.
=> Fix attribute name in pru.request

siriuspy/siriuspy/pwrsupply/pssofb.py, siriuspy/siriuspy/pwrsupply/tests/sofb2bsmp.py
=> Pssofb multiprocessing

siriuspy/siriuspy/clientconfigdb/types/global_config.py
Guys, this is a temporary solution needed to avoid a bug in the low level control of PU
=> MNT: add delays between PU PVs in gloabl_config

siriuspy/siriuspy/pwrsupply/pructrl/prucontroller.py
=> Update PRUController to avoid write bsmp commands while in SOFBMode On

siriuspy/siriuspy/devices/device.py
The Idea is to have absolute control of critical PVs auto_monitor statuses.
=> DEV.ENH: Add property/method do get/set auto_monitor state.

siriuspy/siriuspy/devices/bpm.py, siriuspy/siriuspy/sofb/bpms.py, siriuspy/siriuspy/sofb/orbit.py
Turn BPMs switching on/off when SlowOrb/MultTurn mode is selected.
=> Add SwMode to SOFB

siriuspy/siriuspy/ramp/conn.py, siriuspy/siriuspy/ramp/reconst_factory.py
This PR changes RF connectors to control gap voltage PVs in raw units.
=> Update ramp 

siriuspy/siriuspy/ramp/ramp.py, siriuspy/siriuspy/ramp/reconst_factory.py, siriuspy/siriuspy/ramp/test_reconst_factory.py, siriuspy/siriuspy/ramp/waveform.py
This PR includes BODipRampFactory, a class to reconstruct dipole ramp energies from implemented waveform, and refactor BONormListFactory.
=> Add BODipRampFactory

siriuspy/siriuspy/sofb/__init__.py, siriuspy/siriuspy/sofb/utils.py
Add `utils` module in `SOFB` with function to calculate bumps in the storage ring.
=> Improve SOFB.

siriuspy/siriuspy/devices/__init__.py, siriuspy/siriuspy/devices/lillrf.py, siriuspy/siriuspy/devices/rf.py, siriuspy/tests/test_util.py
Fix redundancy between LLRF classes related to Linac LLRF and AS LLRF (BO and SI)
=> Rename LLRF devices

siriuspy/siriuspy/machshift/csdev.py, siriuspy/siriuspy/machshift/main.py
- Add new shift types: Standby and Shutdown
- Add new AS-Glob:AP-MachShift:ProgmdUsersShift-Mon PV
=> Update MachShift IOC

siriuspy/siriuspy/sofb/correctors.py, siriuspy/siriuspy/sofb/csdev.py, siriuspy/siriuspy/sofb/main.py
Also: Change some default  values to be more adequate for operation.
=> Add Performance Monitoring PVs

siriuspy/siriuspy/clientconfigdb/types/as_rf.py
=> Update clientconfigdb as_rf config

siriuspy/siriuspy/currinfo/__init__.py, siriuspy/siriuspy/currinfo/filling_pattern.py
Add a rudimentary but working class for measurement of beam filling patterns (from andrei's script)
=> Add MeasFillingPattern to currinfo

siriuspy/siriuspy/sofb/main.py
Generate random orbit instead of kicks.
=> Change way SOFB run in tests mode

siriuspy/Makefile
This PR adapts the Makefile to the new pattern suggested in https://github.com/lnls-sirius/hla/pull/513
=> Improve installation

siriuspy/siriuspy/sofb/utils.py
See related PR in https://github.com/lnls-fac/apsuite/pull/173
=> Add sofb bump for b2

siriuspy/siriuspy/devices/__init__.py, siriuspy/siriuspy/devices/egun.py, siriuspy/siriuspy/devices/rf.py, siriuspy/siriuspy/injctrl/csdev.py, siriuspy/siriuspy/injctrl/main.py
- Rename Type-Sts PV to Type-Mon and create a new Type-Sts PV
- Improve injection type change logging 
- Bring RFKillBeam button from siriushla to devices and create a PV that controls it in InjCtrl IOC
- Turn off (and do not allow turning on) AutoStop if RepeatBucketList is different from zero
- Fix unexpected behavior on EGun Bias voltage setpoint
=> Improve InjCtrl IOC

siriuspy/siriuspy/currinfo/main.py
Wait more time for DCCT to update in BO2SI injection efficiency calculation.
=> Fix BO2SI InjEff calc

siriuspy/siriuspy/devices/screen.py
**Improvements**
- Insertion of ScrnCam properties: center offsets and the scale factor to convert pixel to mm.
- Adds properties about the image sizes;
- The image property returns the image reshaped instead of the raw image;
=> Improve screen devices

siriuspy/siriuspy/search/ll_time_search.py, siriuspy/tests/search/test_ll_time_search.py
- Add new LLTimeSearch.get_evg2fout_mapping method
=> Improve LLTimeSearch

siriuspy/siriuspy/devices/__init__.py, siriuspy/siriuspy/devices/egun.py, siriuspy/siriuspy/devices/injsys.py, siriuspy/siriuspy/devices/posang.py, siriuspy/siriuspy/devices/pwrsupply.py, siriuspy/siriuspy/devices/tune.py, siriuspy/siriuspy/injctrl/csdev.py, siriuspy/siriuspy/injctrl/main.py
Hi guys, this PR:
- Adds first version of PosAng device
- Adds first version of InjSysPUModeHandler, that handles the pulsed magnets and PosAng to switch between Accumulation, Optimization and OnAxis configurations
- Adds new PUMode-Sel/Sts PVs in InjCtrl IOC to control InjSysPUModeHandler
- Cleanup code and improve docstrings
=> Improve devices and add new PV to control PU configuration in InjCtrl IOC

siriuspy/siriuspy/timesys/static_table.py
Add URL of google doc excel file for timing system data file creation.
=> Add file URL

siriuspy/siriuspy/devices/egun.py
Hi guys, this PR fixes a bug that caused the InjCtrl IOC to not run EGun HVPS ramp.
=> Fix InjCtrl IOC

siriuspy/siriuspy/devices/pstesters.py
Companion of https://github.com/lnls-sirius/hla/pull/597.
=> Bring PSCommands GUI connectors from siriushla

siriuspy/siriuspy/devices/dvf.py, siriuspy/siriuspy/devices/injctrl.py, siriuspy/siriuspy/devices/injsys.py, siriuspy/siriuspy/devices/pwrsupply.py, siriuspy/siriuspy/devices/rf.py, siriuspy/siriuspy/devices/timing.py
- Add new property and methods to `ASLLRF`.
- Refactor `RFKillBeam`;
- Improve methods of `EVG` to add option to wait for RB PVs in some operations;
- Change `PUMode` of `InjSys` so that `InjDpKckr` and `InjNLKckr` are not turned off.
=> Improve Devices

siriuspy/siriuspy/currinfo/main.py
Make code more robust against oscilloscope configuration changes.
=> Fix CurrInfo

siriuspy/siriuspy/clientconfigdb/configdb_document.py, siriuspy/siriuspy/clientconfigdb/pvsconfig.py
Add option in `ConfigDBDocument` and `PVsConfig` of loading discarded configurations.
=> Improve ConfigDB

siriuspy/siriuspy/clientarch/pvarch.py
This PR adds an improvement suggested by @ericonr .
=> Add setter to PVDataSet pvnames property

siriuspy/siriuspy/devices/timing.py, siriuspy/siriuspy/injctrl/csdev.py, siriuspy/siriuspy/injctrl/main.py
This PR:
- adds missing [commit](ce7e07ad857bf4b5e7afdb9572aaa1b703d84a55) to InjCtrl IOC to work
- rename "LI standby" feature to "LI warm up"
- do not write to bucket list when bucket list start or stop parameters are changed in top-up mode
- add new PVs to control subsystems state between top-up injections
- clean up code
=> Update InjCtrl IOC

siriuspy/siriuspy/injctrl/csdev.py, siriuspy/siriuspy/injctrl/main.py
This PR adds new IsInjecting-Mon PV to InjCtrl IOC: a flag that indicates whether an injection event is occurring. Also, this PR adds related IsInjDelay-SP/RB and IsInjDuration-SP/RB PVs to configure flag delay and duration.
=> Add new PV IsInjecting-Mon 

siriuspy/siriuspy/devices/idff.py, siriuspy/siriuspy/idff/main.py
When IDFF is never connected with EPU
=> Improve IDFF over anomalous IOC condition

siriuspy/siriuspy/optics/lattice_survey.py
depends on https://github.com/lnls-fac/pymodels/pull/95
depends on https://github.com/lnls-fac/pymodels/pull/96/files
=> Improve lattice_survey

siriuspy/siriuspy/devices/__init__.py, siriuspy/siriuspy/devices/blctrl.py
Add BLPPSCtrl device (beamline personal protection system control) to open beamlines (CAX)
=> Add device BLPPSCtrl

siriuspy/siriuspy/clientconfigdb/_templates.py, siriuspy/siriuspy/cycle/util.py, siriuspy/siriuspy/devices/__init__.py, siriuspy/siriuspy/devices/idff.py, siriuspy/siriuspy/devices/ids.py, siriuspy/siriuspy/idff/config.py, siriuspy/siriuspy/idff/csdev.py, siriuspy/siriuspy/idff/main.py, siriuspy/siriuspy/search/id_search.py
depends on https://github.com/lnls-sirius/machine-applications/pull/286/files
=> Add PAPU50

siriuspy/siriuspy/idff/main.py, siriuspy/siriuspy/pwrsupply/tests/sofb2bsmp.py, siriuspy/siriuspy/pwrsupply/tests/test_stress_pwrsupplies.py, siriuspy/siriuspy/sofb/correctors.py
Only import PRUserial485 when it is installed.
=> Remove dependency on PRUserial485.

siriuspy/siriuspy/devices/rf.py
These new features will be used to measure the RF line of AC ORM.
=> Add methods to control conditioning mode.

siriuspy/siriuspy/devices/__init__.py, siriuspy/siriuspy/devices/bpm.py, siriuspy/siriuspy/devices/bpm_eq.py, siriuspy/siriuspy/devices/device.py
companion of lnls-sirius/hla#672
=> Add switching equalization DeviceSet

siriuspy/siriuspy/devices/device.py, siriuspy/siriuspy/devices/injsys.py, siriuspy/siriuspy/devices/rf.py, siriuspy/siriuspy/injctrl/main.py
- Fix bug in InjSys turn off procedure
- Fix tolerance for Egun bias check
- update SI RF devices according to new amplifier tower PV names
- Fix bug in Device properties
=> Fix bugs in Injection Control IOC and update RF devices

siriuspy/siriuspy/search/ll_time_search.py, siriuspy/siriuspy/timesys/csdev.py
Companion of lnls-sirius/control-system-constants#307
=> Create HL Trigger for orbit interlock redundancy

siriuspy/siriuspy/orbintlk/csdev.py, siriuspy/siriuspy/orbintlk/main.py
Making it a single PR for remaining fixes. Code review still in progress.
=> General OrbIntlk fixes

siriuspy/siriuspy/devices/intlkctrl.py
So as to have most diagnostics for failures while opening the beamline.
=> Add error log to BLInterlockCtrl device

siriuspy/siriuspy/idff/csdev.py, siriuspy/siriuspy/idff/main.py
- remove PSSOFB option
- set 10 Hz frequency for IDFF loop as default
- fix bug with default QSControl option
- Add monitoring PVs for calculated corrector setpoints
todo:
=> Remove PSSOFB from IDFF

siriuspy/siriuspy/devices/bpm_eq.py, siriuspy/siriuspy/devices/bpm_fam.py
Add method to calculate positions from antennas amplitudes.
=> Improve FamBPMs

siriuspy/siriuspy/clientconfigdb/types/as_rf.py
BO Pwr sensor, SSA tower 3 and 4 alarm and offset config PVs added
=> Adding BO Pwr sensor, SSA tower 3 and 4 alarm and offset config PVs

siriuspy/siriuspy/dvfimgproc/csdev.py, siriuspy/siriuspy/dvfimgproc/main.py, siriuspy/siriuspy/dvfimgproc/meas.py
- added ImgROITraj PVs with image projections
- defined consts in Const class
- Changed IOC to update PVs that are not of Fit-type even when there is no beam.
ps: Tested!
=> Add imgproc ROIProj PVs

siriuspy/siriuspy/devices/bpm_fam.py
thans to @anacso17 for catching this one!
=> Fix "config_mturn_acquisition"

siriuspy/siriuspy/pwrsupply/beaglebone.py, siriuspy/siriuspy/pwrsupply/csdev.py, siriuspy/siriuspy/pwrsupply/pructrl/prucontroller.py, siriuspy/siriuspy/pwrsupply/psctrl/pscontroller.py, siriuspy/siriuspy/pwrsupply/tests/utils.py
- depends on https://github.com/lnls-sirius/dev-packages/pull/1081 (merged)
- checks:
=> Add wfmoffset strengths

siriuspy/siriuspy/devices/injctrl.py, siriuspy/siriuspy/injctrl/csdev.py, siriuspy/siriuspy/injctrl/main.py
=> Add feature to select which bunches are allowed to inject.

siriuspy/siriuspy/devices/bpm_fam.py, siriuspy/siriuspy/devices/fofb.py
Add option to create family of ID BPMs in `FamBPMs`
=> FamBPMs for ID BPMs

siriuspy/siriuspy/clientconfigdb/types/as_rf.py
Added PVs related to the dynamic interlocks.
Added Quench condition 1 related PVs.
=> Added dynamic interlock PVs

siriuspy/siriuspy/oscilloscope/keysight.py, siriuspy/siriuspy/oscilloscope/scopes.py
- Fixes issues involving `scope_name` and the use of `get_scope_name` method
- Fixes scopes IPs and BO fill pattern channel
- Adds scope signals of LI and TB ICTs, as well as Modulators
=> Fixes and additions of scopes signals

siriuspy/siriuspy/injctrl/bias_feedback.py, siriuspy/siriuspy/injctrl/csdev.py, siriuspy/siriuspy/injctrl/main.py
- add BiasFB PVs to Properties-Cte list
- add TimestampBoot-Cte PV
- Standardize imports
=> Improve injctrl

siriuspy/siriuspy/clientconfigdb/types/as_rf.py
Added PVs related to the new LLRF E-Quench Detection Feature. Also included missing Quench related FIM PVs to the booster section.
=> Added EQuench PVs

siriuspy/siriuspy/devices/ids.py
This PR adds the new VPU for CATERETE and fixes a problem with parameter derivation from IDFullMovCtrl
=> Update devices ids
