lnls-sirius/dev-packages

CODEOWNERS
siriuspy/siriuspy/csdevice/pwrsupply.py
siriuspy/siriuspy/pwrsupply/controller.py
siriuspy/siriuspy/pwrsupply/model.py
siriuspy/siriuspy/pwrsupply/pru.py
siriuspy/siriuspy/ramp/waveform.py
siriuspy/siriuspy/servconf/conf_types.py
siriuspy/siriuspy/servconf/types/rmp_bo_ps.py
siriuspy/tests/csdevice/test_pwrsupply.py

- change pwrsupply classes to allow for length-varying wfmdata setpoints.
- configuration comparisons in servconf will have to be generalized!

Pr wfmdata variable size

---

siriuspy/siriuspy/csdevice/pwrsupply.py
siriuspy/siriuspy/pwrsupply/bsmp.py
siriuspy/siriuspy/pwrsupply/controller.py
siriuspy/siriuspy/pwrsupply/data.py
siriuspy/siriuspy/pwrsupply/model.py
siriuspy/tests/csdevice/test_pwrsupply.py
siriuspy/tests/pwrsupply/test_data.py

- initial steps to generalize set of classes used in PS and MA IOCs so that they can be used for any kind of power supplies (FBP, FAP, etc)

Pr generalize ps types

---

siriuspy/siriuspy/pwrsupply/bsmp.py
siriuspy/siriuspy/pwrsupply/controller.py
siriuspy/siriuspy/pwrsupply/pru.py

- Initially I thought there was a bug in the latest master branch, since the PS IOC was not working in the test bench. 
- Latter, we realized that the PS controller was not responding because of a bug in its firmware triggered when the IOC sent BSMP commands for a PS ID that was not being used. This probably happened at some point last week, when we changed the beagle-bone mapping file;
- Gabriel updated the PS controller with a new firmware which fixes this vulnerability.
- In meantime , a potential bug related to the BSMP variable group creation was fixed in <code>pru.py</code>

Pr fix master real ps

---

siriuspy/siriuspy/pwrsupply/controller.py

Used `PSCStatus` to get the right value for the op mode in the `execute_function` method of the `FBP_BSMPSim`.

Corrected translation op mode in FBP_BSMPSim

---

.gitignore
siriuspy/siriuspy/csdevice/__init__.py
siriuspy/siriuspy/csdevice/const.py
siriuspy/siriuspy/search/ma_search.py
siriuspy/tests/search/test_ma_search.py

The main features of this quick PR are:
- Make `MASearch._manames_list` an ordered list of `SiriusPVName` objects (just like its `PSSearch` counterpart);
- Add method `get_namedtuple` to `csdevice/const.py` module;
- Fix misuse of `collections.namedtuple` in `csdevice.const.Const` class;
- Comment function MASearch.conv_psname_2_maname and its test;
- Rename MASearch.conv_psname_2_maname_pwrsupply to conv_psname_2_psmaname;
Please, let me know if this breaks some of your code.

Small changes in csdevice

---

siriuspy/siriuspy/servconf/conf_service.py
siriuspy/tests/servconf/test_config_service.py

Added two method to `ConfigService`, in order to give access to the new `config_type` endpoint in the configuration database REST API.

Added access to config_type endpoint

---

siriuspy/siriuspy/servconf/srvconfig.py

Remove restriction to `'value'` field. Now it does not need to be a `dict` instance.

Remove dict restriction in value field of configurations.

---

siriuspy/siriuspy/pwrsupply/prucontroller.py

This PR fixes the problem that occurs when the IOC is running, and someone sends the BSMP command `reset_udc`. 
In this command the BSMP entities will be reset, causing all groups to be removed. This leaves the IOC in a states where it continues to read the groups but they don't exist causing the PVs to be disconnected and not being updted.
This PR adds an ack check and create the groups again in case in receives an `invalid_id` response.

Add bsmp_init_group when invalid_id response is received

---

siriuspy/siriuspy/pwrsupply/prucontroller.py

When setting a variable wfmData, `PRUController` had a Ctrl+C/Ctrl+V bug that is fixed in this PR.

Fix problem when setting variable WfmData-SP

---

siriuspy/siriuspy/csdevice/timesys.py
siriuspy/siriuspy/timesys/ll_classes.py

The code sections used to check for the state of Downlink and Fout Downlink properties were commented.
When Timing connections in Sirius timing devices are properly installed, in its final configuration, these sections will be introduced back to the code.

Remove Downlink from HLTrigger Status

---

siriuspy/siriuspy/cycle/conn.py
siriuspy/siriuspy/cycle/main.py
siriuspy/siriuspy/epics/psdiag_pv.py

After cycling finished, set power supplies OpMode-Sel to SlowRef and wait for OpMode-Sts before restore timing initial state. This change bypass bug in timing of sending a new trigger to power supplies when restoring initial state.

Fix PSCycle

---

siriuspy/siriuspy/pwrsupply/functions.py
siriuspy/siriuspy/pwrsupply/prucontroller.py
siriuspy/siriuspy/pwrsupply/psmodel.py
siriuspy/siriuspy/pwrsupply/psupply.py
siriuspy/siriuspy/pwrsupply/tests/utils.py

PS firmware returns *NaN* for some unused parameters, depending on the psmodel. *NaN* always triggers Pv value/timestamp updates, thus generating storage data fro epics archiver. In this PR IOCs will replace *NaN* by numerical zero as default uninitialized value.

Change default value of PS parameters

---

siriuspy/siriuspy/pwrsupply/csdev.py

- Comment out ps-ioc PVs SOFBCurrent-* that were added prematurely by mistake in epics dbase.

Fix PS IOC

---

siriuspy/siriuspy/magnet/excdata.py
siriuspy/siriuspy/magnet/normalizer.py
siriuspy/siriuspy/meas/lienergy/main.py

trivial improvement of excdata methods, useful for the case when only the main harmonic multipole fitting is necessary, such as for control system current-strength conversions.
```python
n = NormalizerFactory.create('BO-01U:MA-CH')
v = [-10 + i/10 * (10 + 10) for i in range(11)]
n.conv_current_2_strength(v, strengths_dipole=3)
```
from ~ 413 us to ~ 54 us.

ExcData interpolation methods optimization

---

siriuspy/siriuspy/devices/psconv.py
siriuspy/siriuspy/magnet/factory.py
siriuspy/siriuspy/meas/liemit/main.py
siriuspy/siriuspy/ramp/magnet.py
siriuspy/tests/magnet/test_factory.py
siriuspy/tests/magnet/tests_normalizer.py

move module siriuspy.factory to subpackage magnet, to where it naturally belongs. I think it was originally located at the top of siriuspy with the ideia that all other factories would eventually be concentrated in this module along the way. practice proved otherwise.

Magnet Factory Relocation

---

siriuspy/siriuspy/csdev.py
siriuspy/siriuspy/sofb/csdev.py
siriuspy/siriuspy/util.py
siriuspy/tests/test_util.py

This PR moves the method `get_namedtuple` from this repo to `mathphys`.
I decided to do this because I needed this function in another repo (`apsuite`) and instead of importing `siriuspy`, I prefer to import `mathphys`, since it is more basic package.
Also, the scope of this method is very general, hence, more suitable for `mathphys` than `siriuspy`.
I noticed there are other methods in `siriuspy` which could be moved to `mathphys`. Maybe we could do that in the future.
OBS.: Tests are failing because the mathphys code (lnls-fac/mathphys#10) was not merged yet.

Move namedtuple

---

requirements.txt
siriuspy/siriuspy/pwrsupply/factory.py
siriuspy/siriuspy/pwrsupply/pructrl/pru.py

This is a companion PR of https://github.com/lnls-sirius/machine-applications/pull/205:
- Move `EthBridgeClient` import to _machine_applications_, keeping _siriuspy_ free of hardware communication protocols other than EPICS.
- Change `requirements.txt` versioning conditionals in order to delegate precise control to _ansible_ configuration.

Move EthBrigdeClient import to machine_application repo

---

siriuspy/siriuspy/devices/device.py
siriuspy/siriuspy/devices/psconv.py
siriuspy/siriuspy/devices/syncd.py

While running tests with ID feedforward classes I realized that _-Mon_ PVs, for which original _Devices_ class turns `auto_mon` to False by default, were taking at least 20 ms in `PV.get`method. Here I added the option of  `auto_mon` to the class init. If set to True, `-Mon` PVs will also be created with  `auto_mon` on.
@fernandohds564 , are you using `auto_mon=False` for PVs in SOFB ? Did you not notice performance degradation?
ps: I just realized that the delay of 20 ms might be due to a test client running across a VPN connection...

Add auto_mon option do Devices class init

---

siriuspy/siriuspy/pwrsupply/pructrl/prucontroller.py

Remove a print option that was preventing diagnostics to be printed when a power supply responded with errors, in certain situations.

Delete bogus print line in prucontroller

---

siriuspy/siriuspy/timesys/ll_classes.py

These updates are not necessary anymore.
Now the raw PVs are in the `global_config`, not the time unit ones.
This update was creating a large and unnecessary amount of data in archiver.

TIM.BUG: Do not update PVs when RF changes.

---

siriuspy/siriuspy/sofb/csdev.py
siriuspy/siriuspy/sofb/orbit.py
siriuspy/siriuspy/sofb/performance_tests/orbit_times.py
siriuspy/siriuspy/sofb/performance_tests/orbit_times_short_term.py

Hi guys, I think I have found a huge source of latency in SOFB code.
This PR fixes it.
Look how is the latency of today's master branch:
And this is the latency of the HEAD of this branch:
I didn't test the code that's running today (v2.9.0) but I'm almost sure it is very close to the master branch.
This latency was measured taking de difference of the BPM timestamps at the moment of the orbit formation and the time measured at the end of SOFB processing, at the very last line of the method which returns the orbit that will be used to calculate the kicks.
So this is a measure of the total latency of the network transmission, the acquisition of this data and processing of the SOFB IOC.
I'm not sure why our master branch was so bad, because I have tested this latency before (more than a …

Improve sofb performance

---

siriuspy/siriuspy/meas/manaca/csdev.py
siriuspy/siriuspy/meas/manaca/main.py

After first interaction with beamline,I noticed a few problems:
- MEAS.MNT: update target x default position: they were asking to center the beam in 375px, not in 372px.
- MEAS.MNT: change signal of y bump: the signal of the y bump was wrong, probably because of the x-flip of the image.

Fix Manaca IOC

---

requirements.txt
siriuspy/siriuspy/sofb/orbit.py

checkout these performance tests for the cases I use in the code:
```
In [1]: import numpy as np
In [2]: import bottleneck as bn
In [3]: a = np.random.rand(20)
In [4]: %timeit np.nanmax(a)
5.17 µs ± 16 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [5]: %timeit bn.nanmax(a)
128 ns ± 0.26 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [6]: %timeit np.nanmin(a)
5.22 µs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [7]: %timeit bn.nanmin(a)
126 ns ± 0.424 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [8]: b = np.random.rand(320)
In [9]: %timeit b.mean()
3.04 µs ± 24.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
In [10]: %timeit bn.nanmean(b)
399 ns ± 1.51 ns per loop (mean ± std. dev. of 7 runs, …
```

use bottleneck package to speedup some critical numpy operations.

---

siriuspy/siriuspy/devices/sofb.py
siriuspy/siriuspy/sofb/csdev.py
siriuspy/siriuspy/sofb/orbit.py

Add PV to acquire triggered data even when SOFB is in another mode, such as SlowOrb of Offline modes.
This option will be useful to study orbit stability even when the orbit correction loop is closed.

MTurnAcquire

---

siriuspy/siriuspy/bsmp/serial.py
siriuspy/siriuspy/pwrsupply/factory.py
siriuspy/tests/bsmp/test_serial.py

After the problem of PS IOC with the QF input stage was diagnosed and temporarily circumvented, and concomitant IOC control of the input and output stages was tried, responses to bsmp requests showed incorrect checksums.
It was then realized that Channel.Lock - that was dropped when optimizing code for PSSOFB - was still necessary for process threads in the IOC in communication topologies that require multiple PRUController objects. This lock is necessary in order to avoid mixing queries and responses from different PRUController objects' scan-and-process threads.
Currently only two power supplies (both still running with legacy firmware and IOC) have this topology: BO dipoles and BO QF. After updating dipoles firmware during machine shutdown in September, only BO QF will remain with a …

Reintroduce bsmp.Channel lock

---

siriuspy/siriuspy/sofb/correctors.py
siriuspy/siriuspy/sofb/csdev.py
siriuspy/siriuspy/sofb/matrix.py
siriuspy/siriuspy/sofb/orbit.py

- Improve printing of error messages for debugging.
- Add PV RespMat-Mon to return processed Respmat.
- Fix source of inconvenient error message in Log-Mon PV:
`unsupported operand type(s) for -: 'NoneType' and 'float'`
- Remove deprecated codes for getting SlowOrb from BPMs.
- Add PV SlowOrbTimeout-Mon to monitor timeout events in orbit formation.

Improve sofb

---

siriuspy/siriuspy/clientweb/implementation.py

fix bug in read_url that concatenated a wrong URL string when trying the second web server.
thanks, @edupcoelho , for noticing the wrong string.

Fix bug in clientweb.read_url redundancy

---

siriuspy/siriuspy/pwrsupply/bsmp/entities.py

SI and TS dipoles.
Fixing according to BSMP specification:

Fix the type of some variables in pwrsupply.bsmp.entities

---

siriuspy/siriuspy/pwrsupply/siggen.py

The interface of SignalTrapezoidal class, used to visualize waveforms, seems to be interpreting `aux_params` ordering differently than PS BSMP spec.

Fix aux_parameters in trapezoidal siggen

---

siriuspy/siriuspy/devices/pwrsupply.py

Fix `pulse` property. It belongs to power supply, not to its timing trigger.

Fix power supply device

---

siriuspy/siriuspy/pwrsupply/psctrl/pscontroller.py

1. **tested with SOFB !**
2. It updates setpoints on a device-by-device basis. The implementation requires that SOFBMode-Sel=Off be issued for all power supplies under a beaglebone, if all setpoints of all these power supplies are to be updated. (differently from just turning readouts back up again, which requires only one command issued for the all devices ina beaglebone)

Add setpoint properties update when SOFBMode moves to Off

---

siriuspy/siriuspy/currinfo/csdev.py
siriuspy/siriuspy/currinfo/main.py

- Limit maximum Transport Efficiency in LI, TB and TS `CurrInfo` to 110% to avoid large number due to measurement errors;
- Standardize precision of PVs.
- Try to fix wrong BO-SI injection efficiency calculation for some pulses.

Fix CurrInfo

---

siriuspy/siriuspy/devices/timing.py
siriuspy/siriuspy/timesys/csdev.py
siriuspy/siriuspy/timesys/hl_classes.py

- add new properties to `Trigger` device.
- add PV `DeltaDelayRaw` to IOC.
- Fix limits of `Duration`, `Delay` and `DelayRaw` PVs to avoid erratic behaviors of low level IOCs.
I tested the IOC changes with the TB timing IOC.

Improve Timing

---

siriuspy/siriuspy/magnet/normalizer.py
siriuspy/siriuspy/pwrsupply/beaglebone.py

- Improves StrengthConv (This PR was tested in TB/TS PS and PU conversion IOCs)
- Add  `wait_for_connection` in connections for dipole/quadfam PVs used by BeagleBone `init` method.
```Python3
#!/usr/bin/env python-sirius
import time
from siriuspy.search import PSSearch
from siriuspy.devices import StrengthConv
proptype = 'Ref-Mon'
corrs = \
PSSearch.get_psnames(dict(sec='SI', dev='CH')) + \
PSSearch.get_psnames(dict(sec='SI', dev='CV'))
psconvs = dict()
t0 = time.time()
for corr in corrs:
psconvs[corr] = StrengthConv(corr, proptype)
print(time.time() - t0)
```
Improvement:
before: 16.45 s
after: 1.41 s

Improve strengthconv

---

siriuspy/siriuspy/clientarch/pvarch.py
siriuspy/siriuspy/clientconfigdb/pvsconfig.py
siriuspy/siriuspy/machshift/macreport.py
siriuspy/siriuspy/machshift/test_macreport.py

MacReports:
- Oversample current data to improve statistics resolution and ignore shift failures lasting less than 60s
- Update tests
Fixes and Maintenance:
- PVsConfig class: do not call `load` method when reading `pvs` property 
- pvarch module: fix import order

Update machine reports

---

siriuspy/siriuspy/pwrsupply/pssofb.py
siriuspy/siriuspy/sofb/correctors.py

With this PR it will not be needed to restart SOFB IOC in case some PowerSupply is disconnected from the serial connection with its BBB. 
With the current version of the code, the loop will be opened and a message with the disconnected power supply will be printed to the IOC log. 
As soon as the power supply is connected again, the loop can be closed again.

Fix PSSOFB so that process doesn't crash in case of SerialError

---

siriuspy/siriuspy/currinfo/main.py

This PR counts on two commits to improve injection efficiency calculation
- Change buffer size of SiriusPVTimeSerie: increase buffer size from 0.4s to 0.5s so that a whole injection period is contemplated by the calculation. This change may lead to erroneous efficiency calculation during current ramping, since points before the penultimate injection may be present in buffer. We haven't noticed this error so far, but it is worth keep looking for it in the next few injections.
- Use maximum instead of last value in deque. This way we guarantee to get the maximum current in case we are injecting and killing the beam during injection optimizaiton studies.
Follow below some graphs showing the impact of these changes on the injection efficiency calculation on inject-kill optimization studies. …

Update injection efficienty calculation

---

siriuspy/siriuspy/devices/__init__.py
siriuspy/siriuspy/devices/bpm.py
siriuspy/siriuspy/devices/timing.py
siriuspy/siriuspy/search/hl_time_search.py
siriuspy/siriuspy/timesys/hl_classes.py

This PR contains:
- Add class to control all HLTiming triggers and events with methods to change triggers source and event delays without changing the associated triggers' total delays.
- Add EVG property called `machine_state`
- Add method in `FamBPMs` class to set all BPMs switching mode.
- Add protection in EVG setters of `continuous_state` and `injection_state` to only change values when needed.

Improve Devices

---

siriuspy/siriuspy/devices/egun.py
siriuspy/siriuspy/devices/injsys.py
siriuspy/siriuspy/injctrl/csdev.py
siriuspy/siriuspy/injctrl/main.py

This PR:
- Updates top-up procedure in InjCtrl IOC:
- Check that RepeatBucketList is non-zero and don't turn off InjectionEvt, as RepeatBucketList now controls the number of pulses the top-up injection performs
- Change how the bucket list is updated in top-up mode
- Remove the deprecated TopUpMaxNrPulses PV and add TopUpNrPulses, which controls the number of pulses each injection will perform
- Do not handle the PU pulse state at the start and stop of injection, as the injection system remains on between pulses
- Following the tests we performed last week, this PR chnage InjBOStandbyHandler cmd_turn_off method to wrap update events with wait intervals to avoid EVG strange behaviors
- Updates the delays in ASPUStandbyHandler according to new values established by Fabio (EPP)
- Updates the …

Update InjCtrl IOC for new topup procedure

---

siriuspy/siriuspy/devices/bpm.py

Improve class interface by explicitly defining properties, instead of attributes that have to be read in the code implementation.

Add bpm_names and csbpm explicit properties

---

siriuspy/siriuspy/clientarch/client.py
siriuspy/siriuspy/machshift/macreport.py

This PR changes ClientArchiver to ignore requests that return json decode errors. This occurs, for example, when archiver retrievel returns requests with results like [this](http://10.0.38.42/retrieval/data/getData.txt?pv=SI-Fam%3APS-Q2%3ADiagStatus-Mon&from=2022-06-01T21%3A41%3A25.571Z&to=2022-07-01T23%3A59%3A25.571Z). Also, it includes minor improvements in MacReport class.

Improve ClientArchiver

---

siriuspy/siriuspy/devices/fofb.py
siriuspy/siriuspy/devices/pwrsupply.py
siriuspy/siriuspy/fofb/csdev.py
siriuspy/siriuspy/fofb/main.py

This PR adds PVs to expose arrays with kicks from CH and CV correctors.
The kicks are calculated from the last values of the currents of each corrector.
The number of points used in the averaging process is defined by PV `KickBufferSize-SP`.

FOFB add KickCH and KickCV

---

siriuspy/siriuspy/devices/device.py

We observed that when some power supply IOCs are restarted, some conversion IOCs such as PU Conv and Fast Corrector Conv crash with "Virtual Circuit Disconnect" event. This commit tries to handle that by also catching CASeverityException in the Device.\_\_getitem\_\_ method.
Detail, error message in fast corrector conversion IOC:
```
Context: "10.128.212.51:45439"
Source File: ../cac.cpp line 1237
Current Time: Mon Oct 17 2022 18:01:51.316379358
..................................................................
CA.Client.Exception...............................................
Warning: "Virtual circuit disconnect"
Context: "10.128.209.50:42394"
Source File: ../cac.cpp line 1237
Current Time: Mon Oct 17 2022 18:01:51.330819729
................................................................ …
```

Avoid crashing on Virtual Circuit Disconnect event

---

siriuspy/siriuspy/cycle/main.py
siriuspy/siriuspy/cycle/util.py
siriuspy/siriuspy/search/id_search.py

This PR:
- Removes new EPU50 feedforward correctors from cycle procedure
- Updates IDSearch with new devices (WIG180 and EPU50)

Update cycle and IDSearch for EPU50

---

siriuspy/siriuspy/clientconfigdb/_templates.py
siriuspy/siriuspy/sofb/main.py

This PR changes SOFB IOC to do not open the FOFB loop when orbit problems are detected, as FOFB already has orbit distortion and packet loss detection functionalities.
Also, this PR replace numpy.typeDict by numpy.sctypeDict, as numpy alias typeDict has been formally deprecated (https://github.com/numpy/numpy/releases/tag/v1.21.0)

Update SOFB IOC

---

siriuspy/siriuspy/callbacks.py
siriuspy/siriuspy/currinfo/lifetime/main.py
siriuspy/siriuspy/currinfo/main.py
siriuspy/siriuspy/devices/injctrl.py
siriuspy/siriuspy/injctrl/bias_feedback.py
siriuspy/siriuspy/injctrl/csdev.py
siriuspy/siriuspy/injctrl/main.py
siriuspy/tests/test_callbacks.py

This PR main feature is the addition of a Bias Feedback to the InjCtrl IOC for topup operation.
The logic of the feedback was inspired in the class added in lnls-fac/apsuite#201. 
Besides this addition, a few other classes were changed:
- Callback: I added a property called `has_callbacks`.
- CurrInfoSI: the InjCurr PV will always be updated when Current3GeV from the booster is updated.
- CurrInfoSI, Lifetime and InjCtrl: the increment of the `-Cmd` was delegated to the Driver class of the IOC. See lnls-sirius/machine-applications#266

Add Topup BiasFB

---

siriuspy/siriuspy/devices/bpm.py
siriuspy/siriuspy/devices/pwrsupply.py
siriuspy/siriuspy/devices/timing.py

Features:
- add method to `PowerSupply` device to set strength and wait for monitor/readback to get there;
- Remove auto-monitor of array PVs in `FamBPMs`;
- Improve method `get_sampling_frequency` and make it a regular object method instead of a `staticmethod`
- Improve logic of checking whether triggered acquisition finished sucessfully. Now the flow of a triggered acquisition should be like this:
```python3
fambpms = FamBPMs()
need_sum = True
ret = fambpms.mturn_config_acquisition()  #use as input here the necessary configurations
if ret < 0:
raise Exception(f'BPM {-ret-1:d} did not finish last acquisition.')
elif ret >0:
raise Exception(f'BPM {ret-1:d} is not ready for acquisition.')
fambpms.mturn_update_initial_orbit(consider_sum=need_sum)
ret = …
```

Fixes devices

---

siriuspy/siriuspy/magnet/factory.py
siriuspy/siriuspy/magnet/normalizer.py

- Fix bug in initializer of TrimNormalizer.
- Add optional attribute called `default_strengths_dipole` to normalizer classes to avoid having to define `strengths_dipole` on every conversion call.
- Remove unused hiden module constants.

Improve Normalizer

---

siriuspy/siriuspy/epics/__init__.py
siriuspy/siriuspy/epics/threading.py
siriuspy/siriuspy/sofb/base_class.py
siriuspy/siriuspy/sofb/bpms.py
siriuspy/siriuspy/sofb/correctors.py
siriuspy/siriuspy/sofb/main.py
siriuspy/siriuspy/sofb/matrix.py
siriuspy/siriuspy/sofb/orbit.py

This PR:
- Creates a class `CAThread` derived from `pyepics.ca.CAThread` to be used in threading when PVs handling is needed;
- Starts using this class in SOFB;
- Changes all SOFB setpoint methods which require some calculation or validation so that they return as fast as they can, leaving the hard work to threads.

Upgrade SOFB

---

siriuspy/siriuspy/devices/bpm.py

- fix some bugs introduced in commit 1449303.
- Start using recently created PV `ACQCount-Mon`, which is incremented every time an acquisition is finished, to indicate whether triggered acquisitions are ready to be assembled in an orbit. Thanks to @ericonr for implementing this PV!.

Fix BPM and FamBPMs

---

siriuspy/siriuspy/pwrsupply/csdev.py
siriuspy/siriuspy/search/ps_search.py
siriuspy/tests/pwrsupply/test_csdev.py
siriuspy/tests/search/test_ps_search.py

This PR adds methods to provide the information of the table of memory addresses for power supplies scope source ([available in wiki-sirius](https://wiki-sirius.lnls.br/mediawiki/index.php/ELP:Table_of_memory_addresses_for_power_supplies_Scope_Source)). 
Also (forgot to separate in a commit, sorry) this PR removes a nonexistent PV (PSStatus-Mon) listed in fast corrector database.

Improve PSSearch and PS csdev

---

.github/workflows/test-siriuspy.yml

This PR fixes recent bug raised by new pip versions (other PRs are failing in tests because a new pip version is available which requires `wheel` for package installation).

Fix siriuspy tests

---

siriuspy/siriuspy/clientconfigdb/types/as_diagnostics.py
siriuspy/siriuspy/devices/device.py
siriuspy/siriuspy/devices/fofb.py
siriuspy/siriuspy/devices/pwrsupply.py
siriuspy/siriuspy/fofb/main.py

This PR updates FOFB related classes according to new FOFB controllers IOC version:
- now we have RefOrbX and RefOrbY PVs, instead of only RefOrb
- equivalently, we have InvRespMatRowX and InvRespMatRowY, instead of InvRespMatRow
- CCEnable-RB PV was renamed to CCEnable-Sts
Also, this PR:
- separates FOFB IOC periodic checks in two threads, one for correctors and the other to controllers
- add FOFB controllers physical triggers PVs to as_diagnostics config

Adapt classes and devices to new FOFB controllers IOC version

---

siriuspy/siriuspy/devices/bpm.py

This PR updates FamBPMs device:
- remove wait methods that use orbit comparison
- add methods to verify that data was updated using PVs timestamp
- fix docstrings and implement some linting suggestions
Maybe the changes here will trigger changes in `apsuite`, I will verify it, but if you guys notice some undesired API change, please let me know.

Update FamBPMs device

---

siriuspy/siriuspy/devices/device.py

This PR fixes a bug we noted yesterday during machine studies, this commit changes Device class to create PVs with the correct auto_monitor setting. Thanks to @fernandohds564 and @ericonr for helping me debug this.

Fix bug in Device class

---

siriuspy/siriuspy/diagsys/psdiag/csdev.py
siriuspy/siriuspy/diagsys/psdiag/main.py
siriuspy/siriuspy/diagsys/psdiag/pvs.py

This PR updates PSDiag IOC:
- DiagStatus PV now also checks whether fast correctors are with triggered mode disabled;
- DiagCurrentDiff PV calculates Diff considering CurrentRef-Mon for fast correctors when those are in FOFB mode, and DiagStatus PV checks CurrentDiff also in FOFB mode.

Update PSDiag IOC

---

siriuspy/siriuspy/machshift/gensumm_macreport.py
siriuspy/siriuspy/machshift/macreport.py
siriuspy/siriuspy/machshift/macschedule.py
siriuspy/siriuspy/machshift/savedata_macreport.py

This PR:
- Adapts MacScheduleData class to correct count shifts that last longer than a day
- Adds snippet to generate raw data .csv file (used for internal audit activities)
- Updates script for generating machine report summary
- Adds minor improvement in MacScheduleData.get_users_shift_day_count to make it possible to choose whether to count sunday as a user shift day

Update machine report scripts

---

siriuspy/siriuspy/sofb/csdev.py
siriuspy/siriuspy/sofb/orbit.py

Hi guys, this PR has a huge simplification of the SOFB code, thanks to @ericonr.
The new orbit IOC gets the orbit from all BPMs using a similiar algorithm as the one SOFB used to use, but it is much faster and reliable because it is not implemented in python.
At first I tested the sanity of the PV provided by the orbit IOC:
```python3
import time
import numpy as np
import matplotlib.pyplot as mplt
from siriuspy.epics import PV
from siriuspy.sofb.orbit import EpicsOrbit
orbs = []
tims = []
tstmps = []
def callback(pvname, value, **kwrgs):
orbs.append(value)
tims.append(time.time())
tstmps.append(kwrgs['timestamp'])
orb_pv = PV('SI-Glob:AP-SOFB:SlowOrbRaw-Mon')
orb_pv.wait_for_connection()
orb_pv.add_callback(callback)
time.sleep(10)
orb_pv.clear_callbacks()
orbs = np.array(orbs)
tims = …
```

Change SOFB to use SlowOrb from Orbit IOC.

---

siriuspy/siriuspy/clientconfigdb/types/as_diagnostics.py
siriuspy/siriuspy/clientconfigdb/types/global_config.py
siriuspy/siriuspy/search/hl_time_search.py
siriuspy/siriuspy/timesys/ll_classes.py

This PR : 
- adds high level PsMtn BPM trigger
- fixes a bug in HLTiming IOC that was causing erroneous Evt number parsing
- removes from as_diagnostics configuration the AMCFPGAEVR PVs that are controlled by HL triggers

Add PsMtn BPM trigger to global_config.

---

siriuspy/siriuspy/clientconfigdb/types/global_config.py

Since now these correctors are used in the IDFF loop control.

Remove EPU correctors from global config

---

siriuspy/siriuspy/devices/orbit_interlock.py
siriuspy/siriuspy/diagbeam/bpm/csdev.py

Add option to calculate a minimum between downstream and upstream BPM metric

Update orbit interlock device

---

siriuspy/siriuspy/timesys/csdev.py

@anacso17 informed me that some char array PVs from the high level timing IOCs were causing instabilities on the PV Gateway. She told me the problem was related to PVs whose value length exceeded the `'count'`  of the PV. Namely, the following PVs:
```
SI-Glob:TI-Mags-Corrs:CtrldChannels-Cte
SI-Glob:TI-Mags-QTrims:CtrldChannels-Cte
```
I noticed the definition of the above mentioned field was hard-coded.
I changed it to be defined according to the real length of each value.

TIM.BUG: Fix length of some char array PVs.

---

siriuspy/siriuspy/devices/scraper.py

This PR renames slits naming:
```
Inner -> Right
Outer -> Left
```
The changes were triggered by the conversation in this PR: https://github.com/lnls-sirius/dev-packages/pull/998 and will be deployed with this changes: https://github.com/lnls-sirius/diff-ctrl-epics-ioc/commit/60dac2f97862d334fa2c1a70614e091ea0df9911.

Update ScraperH properties according to new IOC pvnames

---

siriuspy/siriuspy/orbintlk/main.py

It was necessary to add a default argument to
_handle_reliability_failure so it could handle the BPM interlock event without printing a misleading message.

orbintlk.MNT: de-duplicate FATAL log messages.

---

siriuspy/siriuspy/devices/energy.py
siriuspy/siriuspy/devices/psconv.py
siriuspy/siriuspy/devices/syncd.py
siriuspy/siriuspy/simul/simps.py
siriuspy/siriuspy/simul/simulator.py

You guys should have objected this standard a long time ago. It would have avoided several minutes of argument typing at this point, probably ! :) 
I also consistently used the naming `*_set(...` for methods in `pwrsupply` subpackage classes. But I dont think it is necessary to adapt non-device classes.

Adapt Device methods naming to consensus standard

---

siriuspy/siriuspy/devices/bpm.py
siriuspy/siriuspy/devices/bpm_eq.py
siriuspy/siriuspy/devices/bpm_fam.py
siriuspy/siriuspy/injctrl/bias_feedback.py
siriuspy/siriuspy/orbintlk/main.py

- Standardize method names.
- Add method to check if data updated in triggered acquisitions. We noted in some AC ORM measurements that only checking for the timestamps was not enough.

Fix FamBPMs

---

siriuspy/siriuspy/search/ps_search.py

siriuspy is broken for script  `sirius-script-app-ps-pvsprint.py`. this PR fixes this.

Fix missing PS type in PSSearch

---

siriuspy/siriuspy/machshift/macreport.py

- Add a new item in MacReport.FAILURES_MANUAL for registering archiver appliance failure related to power grid failure at January 18th

Add manual annotation for January 18th power grid failure in MacReport

---

siriuspy/siriuspy/devices/dvf.py

During this shutdown, Carcará-X (CAX) beamline had its camera IOCs upgraded. This implied in some changes in PV names that were abstracted by the `DVF` device. Update them accordingly.
Whenever possible, they have been replaced by their [ADDriver standard names][1], since they are more stable. Unfortunately, that's not always the case. Since the accelerator cameras still operate with the previous driver, naming conversion is still implemented for BO_DVF.
Such conversions should be entirely removed from this abstraction layer when high-level PVs (see cnpem/ad-aravis-epics-ioc#3)  are tested and deployed for CAX as well, which will happen as a second step.
[1]: https://areadetector.github.io/areaDetector/ADCore/ADDriver.html

Update DVF PVs after IOC upgrade

---

siriuspy/siriuspy/devices/rf.py
siriuspy/siriuspy/orbintlk/csdev.py
siriuspy/siriuspy/orbintlk/main.py

Ana:
-  Add new redundancy EVRs for 08 and 14 sectors
- TODO: update LLRF PVs to use new IOC version, @murilobalves , could you please continue implementations in this PR? 
Murilo:
To be merged in companion with this PR https://github.com/lnls-sirius/dev-packages/pull/1110
- TODO: Discuss proper way to deal with two LLRF systems

Update orbit interlock IOC for new RF configurations

---

siriuspy/siriuspy/orbintlk/csdev.py
siriuspy/siriuspy/orbintlk/main.py

Solves https://github.com/lnls-sirius/dev-packages/issues/1115.
- Monitor both LLRF configurations and both RF EVEs

Update orbit interlock IOC

---

siriuspy/siriuspy/devices/bpm.py

The PV name was correct in the properties list, but wrong in the setter and getter. This also caused the BPM Device to report itself as disconnected, if it was initialized with connection to all BPM PVs.

DEV.FIX: fix PV name in BPM device.

---

siriuspy/siriuspy/devices/idff.py
siriuspy/siriuspy/idff/main.py

Lately the IDFF device was modified in order to add PVs of the IDFF controller itself, besides those of the ID and those related to correctors. This is convenient for jupyter notebooks that deal with various aspects of the FF system. But the high level FF IOC itself uses the IDFF device. An additional option was added in the IDFF device constructor that allows for choosing when to add the IDFF Ctrl device to the devices set.

Fix IDFF device use in IDFF IOC class

---

siriuspy/siriuspy/clientarch/pvarch.py

Added properties `PVDataSet.archived`, `PVDataSet.not_archived`  to list which PVs from a `PVDataSet` object are currently being archived or not.

Show which PVs of a PVDataSet  are archived/not archived

---

siriuspy/siriuspy/devices/dvf.py

recently CAX beamline has been optimized with a different photon beam  position at M1. 
incoming visible flux in the CCD has lowered considerably. 
we increased the default exposure time in order to improve signal/noise ratio.

Update DVF default exposure time

---

siriuspy/siriuspy/util.py

This makes the code that uses siriuspy less restricted to some dependencies, such as pyepics, if it is only using ps_search.

Remove dependency on pyepics.

---

siriuspy/siriuspy/cycle/util.py

- Include comments to explicitly document that new VPU correctors will not be included in cycle procedure
- Improve code documentation
New correctors were added as known type corrector-horizontal at companion PR at control-system-constants (lnls-sirius/control-system-constants#337), if we need to create a new type, let us implement this modifications in this PR.

Update subpackages to handle new correctors

---

siriuspy/siriuspy/search/ll_time_search.py
siriuspy/siriuspy/timesys/static_table.py
siriuspy/tests/search/test_ll_time_search.py

This version of the function removes all unused timing connections from the used connections list and add them to the unused connections list.
The previous version failed to do this for timing connections ending before any trigger source component (EVE, EVR and AMCFPGAEVR) was reached from EVG.

Update function create_static_table

---

siriuspy/siriuspy/injctrl/main.py

- To test what has been speculated: the PU magnets might be put into standby at an instant too close to the instant they pulse and  the standby behaviour observed in the past weeks might be explained by this.

Add wait_time in wait_injection for the injection IOC

---

siriuspy/siriuspy/pwrsupply/bsmp/commands.py
siriuspy/siriuspy/pwrsupply/pructrl/prucontroller.py

UDC firmware is erroneously responding with an timeout error when calling cfg_wfmref. So to avoid unnecessary logging we are going to suppress any error log from this command. This became a problem since SOFB sync mode uses waveform mode.

pwrsupply.ENH: suppress error logging for WfmOffset variable setpoint

---

siriuspy/siriuspy/devices/idff.py

This PR adds the new set_currents method to rampup_corrs and fixes the VPU idff name.

Use set current in IDFF rampup_corr_currents

---

siriuspy/siriuspy/clientconfigdb/types/as_rf.py

The SIA and SIB FIM quench pvs were with -Sts sufix instead of -Sel.

Fixed FIM quench pvs

---

siriuspy/siriuspy/devices/fofb_acq.py

As observed experimentally (SP=-0.15481 and RB=-0.15475), a lower precision must be used for these values. Otherwise, the application of the values is considered to have failed, and the control flow [1] doesn't progress to actually enabling the PRBS functionality.
[1] https://github.com/lnls-fac/apsuite/blob/b2152979aa6b08eb688f80a45690a3119dd5c6b7/apsuite/commisslib/meas_fofb_sysid.py#L373

FOFB.FIX: update atol for PRBS levels.

---

siriuspy/siriuspy/sofb/main.py
siriuspy/siriuspy/thread.py

SOFB was not updating `RefKick`, `FOFBDownloadKicks` and `FOFBDeltaRefOrb` PVs. This PR fixes this problem.

SOFB: Fix Update of Some PVs.

---

siriuspy/siriuspy/devices/device.py
siriuspy/siriuspy/devices/pwrsupply.py

As it is the strength property in PwrSupply is unnecessary being created at device creation even if it is not being defined in props2init.

Improve device PwrSupply

---

siriuspy/siriuspy/clientconfigdb/types/as_corrloop_params.py
siriuspy/siriuspy/sofb/csdev.py
siriuspy/siriuspy/sofb/main.py
siriuspy/siriuspy/sofb/orbit.py

This PR improves the interplay of both systems by adding a PV to control the rate of FOFB reference orbit update when both loops are closed. It was already tested with beam, where it was noted that updating the FOFB reference orbit always leads to zero DC kicks on FOFB correctors and on delta kicks of the slow correctors.
Today, when some BPM of the FOFB loop has a non-zero value in some orbit signature that is on the null-space of the SOFB response matrix, the FOFB tries to correct this distortion, which makes the resulting orbit not to be on the null-space of the SOFB loop. This makes SOFB try to correct this projection, trying to recover the null-space residue again. When this happens, the loops do not aggree on which state should be the correct one, leading to a non-zero DC strength …

Improve SOFB-SOFB interplay
